### ISSUE TITLE
about your model

### ISSUE THREAD

**Issue by zdxiang** [hequnsky/Gank#2]
看网上那些mvp例子，在model层里，不是一个实体javaBean，而是做请求数据之类的操作，如UserModel，IUserModel这些。为什么你会把数据请求处理等放在Presenter层，就像是一个controller一样。望告知原因道理。Thank you

**Comment by hequnsky** [comment]
MVP is a kind of architecture philosophy, you say this is true, but it as a demo project, without involving the business logic of the deep, we are only MVP to very comfortable to use, but a lot more classes and packages, easy to cause a bloated feeling to the person, so rather than regenerate a Model, do not need to write the Model layer, operating Bean directly, rather simple, my MVP patterns are in the phase of exploration, hope I can write a robust architecture!

**Comment by zdxiang** [comment]
@hequnsky I think it is true what you said. As you said,"do not need to write the Model layer". You solve my doubts.Thanks

**Comment by hequnsky** [comment]
Thank you very much for giving me your comments, you can send me E-mail or add my QQ to discuss technology!
